branches: ['+([0-9])?(.{+([0-9]),x}).x', 'main', 'next', 'next-major', {name: 'beta', prerelease: true}, {name: 'alpha', prerelease: true}]
preset: conventionalcommits # https://www.conventionalcommits.org/
tagFormat: "v${version}"
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - - "@google/semantic-release-replace-plugin"
    - replacements:
        - files: [ "Makefile"]
          from: "VERSION \\?= .*"
          to: "VERSION ?= ${nextRelease.version}"
          countMatches: true
          results:
            - file: "Makefile"
              hasChanged: true
              numMatches: 1
              numReplacements: 1
  - - "@semantic-release/git"
    - assets:
        - "CHANGELOG.md"
        - "Makefile"
      message: "chore(release): ${nextRelease.version} [skip ci]"
  - "@semantic-release/github"