# permissions for end users to view copyresources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: copyresource-viewer-role
rules:
- apiGroups:
  - resource.w3tec.ch
  resources:
  - copyresources
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - resource.w3tec.ch
  resources:
  - copyresources/status
  verbs:
  - get
