apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-copier
  labels:
    app: k8s-copier
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-copier-deployment
spec:
  selector:
    matchLabels:
      app: k8s-copier
  replicas: 1
  template:
    metadata:
      labels:
        app: k8s-copier
    spec:
      serviceAccountName: k8s-copier
      containers:
        - name: k8s-copier
          image: dweber019/k8s-copier:0.0.1
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 100m
              memory: 30Mi
            requests:
              cpu: 100m
              memory: 20Mi
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k8s-copier-role-binding
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: manager-role
subjects:
  - kind: ServiceAccount
    name: k8s-copier
    namespace: <namespace>