---
apiVersion: v1
kind: Namespace
metadata:
  name: namespace-one
---
apiVersion: v1
kind: Namespace
metadata:
  name: namespace-two
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-one
stringData:
  username: admin
  password: t0p-Secret
---
apiVersion: resource.w3tec.ch/v1alpha1
kind: CopyResource
metadata:
  name: copyresource-one
spec:
  kind: Secret
  metaName: secret-one
  targetNamespace: namespace-one
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-two
stringData:
  secret: two
  update: awesome
---
apiVersion: resource.w3tec.ch/v1alpha1
kind: CopyResource
metadata:
  name: copyresource-two
spec:
  kind: Secret
  metaName: secret-two
  targetNamespace: namespace-two